version: '3'
services:
  web:
    build: .
#    context: /root/compose/composetest
#    dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
