version: "3.7"
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
    secrets:
      - my_secret
      - my_other_secret
secrets:
  my_secret:
    file: ./my_secret.txt
  my_other_secret:   #my_other_secret is created from "docker secret create my_other_secret ./secret.json" command, docker secret ls gives the gives the secret available in docker daemon, as we are using this secret from docker , so external will be true 
    external: true

